### PR TITLE
Use @krakenjs npm scope

### PR DESCRIPTION
**Pull request by westeezy**
Moving to krakenjs scope for team management

### CODE REVIEW

**Review by wsbrunson — APPROVED** [review]
We'll want to check that https://github.com/paypal/paypal-sdk-release handles this correctly but otherwise 👍

**Comment by westeezy** [comment]
Yeah definitely @wsbrunson. The plan is to merge this after we know all the places we will need to update. Likely we want to coordinate PRs across repos that consume this library before merging this one. I will do a publish ahead of time just so we are able to use it scoped OR unscoped in the interim time.

**Comment by wsbrunson** [comment]
For sure. I think grabthar-release and sdk-release will be able to reflect the new folder path in the cdn folder but I haven't seen the code where it would happen. I'm with you, publish this package and then we can figure out how to modify those tools if we need to.

**Review by gregjopa — APPROVED** [review]

**Comment by westeezy** [comment]
updated unpkg link on demo page

**Review by wsbrunson — APPROVED** [review]

**Pull request merged**
